<?php // this is an autogenerated file - do not edit (created Wed, 09 Feb 2011 08:18:01 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'v6tools\\eui64' => '/EUI64.php',
            'v6tools\\ipv6address' => '/IPv6Address.php',
            'v6tools\\runtime' => '/Runtime.php',
            'v6tools\\subnet' => '/Subnet.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
